boot.o: boot.S multiboot.h x86_desc.h types.h
linkage.o: linkage.S
x86_desc.o: x86_desc.S x86_desc.h types.h
filesystem.o: filesystem.c filesystem.h types.h multiboot.h lib.h
i8259.o: i8259.c i8259.h lib.h types.h
idt.o: idt.c idt.h x86_desc.h types.h lib.h keyboard.h linkage.h pcb.h \
  rtc.h filesystem.h terminal.h i8259.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h keyboard.h rtc.h paging.h filesystem.h terminal.h
keyboard.o: keyboard.c lib.h types.h i8259.h keyboard.h terminal.h
lib.o: lib.c lib.h types.h i8259.h terminal.h
paging.o: paging.c paging.h lib.h types.h
pcb.o: pcb.c pcb.h types.h rtc.h filesystem.h terminal.h lib.h
rtc.o: rtc.c i8259.h lib.h types.h rtc.h
sys_call.o: sys_call.c linkage.h types.h pcb.h rtc.h filesystem.h \
  terminal.h x86_desc.h sys_call.h paging.h lib.h
terminal.o: terminal.c keyboard.h terminal.h types.h lib.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h filesystem.h rtc.h \
  i8259.h
