boot.o: boot.S multiboot.h x86_desc.h types.h
linkage.o: linkage.S x86_desc.h types.h sys_call.h lib.h
x86_desc.o: x86_desc.S x86_desc.h types.h
filesystem.o: filesystem.c filesystem.h multiboot.h types.h x86_desc.h \
  lib.h i8259.h debug.h tests.h idt.h keyboard.h rtc.h paging.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h x86_desc.h types.h lib.h keyboard.h linkage.h rtc.h \
  i8259.h filesystem.h multiboot.h debug.h tests.h paging.h pcb.h \
  sys_call.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h keyboard.h rtc.h paging.h filesystem.h terminal.h
keyboard.o: keyboard.c lib.h types.h i8259.h keyboard.h terminal.h
lib.o: lib.c lib.h types.h i8259.h linkage.h terminal.h
paging.o: paging.c paging.h types.h lib.h
pcb.o: pcb.c pcb.h sys_call.h lib.h types.h
rtc.o: rtc.c lib.h types.h i8259.h rtc.h
sys_call.o: sys_call.c linkage.h sys_call.h lib.h types.h filesystem.h \
  multiboot.h x86_desc.h i8259.h debug.h tests.h idt.h keyboard.h rtc.h \
  paging.h pcb.h
terminal.o: terminal.c keyboard.h lib.h types.h terminal.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h filesystem.h \
  multiboot.h i8259.h debug.h idt.h keyboard.h rtc.h paging.h
