boot.o: boot.S multiboot.h x86_desc.h types.h
linkage.o: linkage.S
x86_desc.o: x86_desc.S x86_desc.h types.h
filesystem.o: filesystem.c filesystem.h multiboot.h types.h x86_desc.h \
  lib.h i8259.h debug.h tests.h idt.h keyboard.h rtc.h paging.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h x86_desc.h types.h lib.h keyboard.h linkage.h rtc.h \
  i8259.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h keyboard.h rtc.h paging.h filesystem.h
keyboard.o: keyboard.c lib.h types.h i8259.h keyboard.h
lib.o: lib.c lib.h types.h i8259.h linkage.h
paging.o: paging.c paging.h types.h lib.h
rtc.o: rtc.c lib.h types.h i8259.h rtc.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h filesystem.h \
  multiboot.h i8259.h debug.h idt.h keyboard.h rtc.h paging.h
